FROM python:3.12-slim
WORKDIR /app

# install deps
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# copy code + frontend
COPY . .

# expose the FastAPI port
EXPOSE 4777

# start the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4777", "--reload"]
